### PR TITLE
Add sort, pagination and search to members list at team page

### PR DESCRIPTION
**Pull request by vgeorge**
This adds an input component to the members' table on the team page to allow search by username. Contributes to https://github.com/developmentseed/osm-teams/issues/319. 

Changes added:

- Refactored Cypress tasks names for consistency
- Added client-side pagination, sort, and search to the members' table
- Added client-side pagination, sort, and search to the explore teams page

@kamicut @LanesGood ready for review

### CODE REVIEW

**Comment by vgeorge** [comment]
@LanesGood @kamicut please hold your review, I want to include some changes from #367 here.

**Comment by vgeorge** [comment]
@LanesGood @kamicut I've merged changes from develop and now the behavior of the search input should be consistent across tables (auto-submit after 1s). I also added pagination and search to the explore teams page. This is ready for review.

**Review by kamicut — APPROVED** [review]

**Comment by kamicut** [comment]
@vgeorge @LanesGood I've approved, but there is this small UI issue (Safari Browser)
image

**Comment by vgeorge** [comment]
@kamicut @LanesGood let's merge this and improve the input separately.

**Pull request merged**
