### PR TITLE
Redirect invite accepted to team page on success

### LINKED ISSUE #371: Invitation Accepted page should prompt a mapper to edit their profile
Currently, when you accept an invitation link, you land here: 
image

There aren't any interactions on the page. 

It would be helpful if this page either had links to "edit your profile" or "go to team" or even automatically landing on the edit profile page instead of this page at all would be even better.

### PR DESCRIPTION
**Pull request by LanesGood**
Redirects the "Invitation accepted" page to the team page of the invite after 3 seconds. This redirect occurs only on a successfully accepted invitation. 

Closes #371 

-_NB_, #371 suggests redirecting immediately to the Team profile. Given the possibility of a user not understanding the new team page invite, I propose redirecting only to the team page. This could later highlight the need to edit and fill the profile.

### CODE REVIEW

**Comment by kamicut** [comment]
@LanesGood This worked! I was a little surprised that we didn't have a confirm before the redirect when going to the URL. When accessing the URL, should we have a "join team" button?

**Comment by LanesGood** [comment]
@kamicut the automatic join is part of the API, as far as I'm aware. This PR doesn't change the existing behavior of the app, which is:
- team moderator creates join link
- team moderator can send join link to anyone
- recipient creates an account and loggs in
- Visiting the link as a logged in OSM teams account holder automatically adds that user to the team

There would need to be an addition to the API to first require a "join team" confirmation. That's out of the scope of this PR but could be a new issue.

**Comment by LanesGood** [comment]
To update:
- [ ] Redirect directly to "edit your profile"
    - Handle updates when no profile attributes exist
- [ ] add "redirecting..." text

**Comment by LanesGood** [comment]
@kamicut updated with text and manual options:
image

**Review by kamicut — APPROVED** [review]

**Pull request merged**
