### PR TITLE
Add OSM users by username

### PR DESCRIPTION
**Pull request by willemarcel**
Contributes to #97

It first searches in the osm teams database. If it doesn't find a user, then we search in OSM. 

It's missing to modify the frontend yet.

### CODE REVIEW

**Comment by willemarcel** [comment]
@LanesGood thanks for the feedback! I'll make the changes you suggested. I prefer to keep the modal open.

**Comment by LanesGood** [comment]
Thanks for debugging with me @willemarcel! As you saw on the slack, i don't see the issue when I reload... though I did see it again a little, I'm not sure how to reproduce but will let you know if it continues to pop up.

I pushed up some styling changes for the form field layout:
image

Finally, I noticed that there are no error notifications/toasts when a user adds a member twice, or when they try to add themselves. I think this is restricted at the API level, and I see no console or network errors, so I'm guessing that we should make some UI changes.

**Review by LanesGood — APPROVED** [review]
I think this works great and is a much welcomed addition! I'll defer to @kamicut on model/data review.

To confirm, does this cache searches for the OSM database? Are these usernames cached in the osm teams database and now available without hitting OSM for all OSM Teams users?

**Comment by willemarcel** [comment]
> To confirm, does this cache searches for the OSM database? Are these usernames cached in the osm teams database and now available without hitting OSM for all OSM Teams users?

I didn't implement cache. When the user search, we try first to find the user in the OSM Teams database, if it's not found, we fetch the OSM API.

**Review by kamicut — APPROVED** [review]
LGTM!

There was a small issue where at some point the "+ Add" button "froze", but after refreshing the page I couldn't replicate the bug. I'm not sure what it could be. If we see this happen again we can open an issue.

**Pull request merged**
