### PR TITLE
Migrate API routes

### PR DESCRIPTION
**Pull request by vgeorge**
The overall goal of this PR is to migrate the API routes from the custom express server to Next.js API handlers and fix data loading on the client side. This PR is built on top of `next-auth` implementation in #302, and contributes to #258 and #71. We are using [next-connect](https://www.npmjs.com/package/next-connect) module, which provides a drop-in replacement for Express in Next.js. 

Changes:

- Added `next-connect` handler to catch all route at `src/pages/api/[[...slug]].js`
- Added `user_id` to the session
- Fixed Sidebar component authenticated state
- Small updates into existing permissions middleware
- Add better API error handling by returning Boom errors on every error
- Return 404 status with Boom-like message on non-existing routes

Currently, the app can load the list of teams from the API and create a new team.

This is a work in progress.

cc @kamicut

### CODE REVIEW

**Comment by vgeorge** [comment]
In order to track better the progress of this PR, this is the full list of pages that need to be reconnected to the API:

- [ ] [/clients](http:localhost:3000/clients)
- [ ] [/teams/create](http:localhost:3000/teams/create)
- [ ] [/teams/:id](http:localhost:3000/teams/:id)
- [ ] [/teams/:id/edit](http:localhost:3000/teams/:id/edit)
- [ ] [/teams/:id/edit-profiles](http:localhost:3000/teams/:id/edit-profiles)
- [ ] [/teams/:id/profile](http:localhost:3000/teams/:id/profile)
- [ ] [/teams/:id/invitations/:uuid](http:localhost:3000/teams/:id/invitations/:uuid)
- [ ] [/organizations/create](http:localhost:3000/organizations/create)
- [ ] [/organizations/:id](http:localhost:3000/organizations/:id)
- [ ] [/organizations/:id/edit](http:localhost:3000/organizations/:id/edit)
- [ ] [/organizations/:id/edit-profiles](http:localhost:3000/organizations/:id/edit-profiles)
- [ ] [/organizations/:id/edit-privacy-policy](http:localhost:3000/organizations/:id/edit-privacy-policy)
- [ ] [/organizations/:id/profile](http:localhost:3000/organizations/:id/profile)
- [ ] [/organizations/:id/edit-team-profiles](http:localhost:3000/organizations/:id/edit-team-profiles)
- [ ] [/organizations/:id/badges/add](http:localhost:3000/organizations/:id/badges/add)
- [ ] [/organizations/:id/badges/:badgeId](http:localhost:3000/organizations/:id/badges/:badgeId)
- [ ] [/organizations/:id/badges/assign/:userId](http:localhost:3000/organizations/:id/badges/assign/:userId)
- [ ] [/organizations/:id/badges/:badgeId/assign/:userId](http:localhost:3000/organizations/:id/badges/:badgeId/assign/:userId)

**Comment by LanesGood** [comment]
@vgeorge I'm able to start the application, but it seems I am having difficulty with the OSM connection/auth.

I followed all instructions in the readme verbatim. On my first login attempt I see the following if I try to authorize the app from the OSM application auth page:
image

I'm then able to login if I click "Wign with OpenStreetMap."

However, I then see `Welcome, !` on the home screen - the app indicates that I'm logged in, but its not getting my username. I see the below when I try to load my profile:
image

I do see in my console that after running `yarn dev` my terminal states `ready - started server on 0.0.0.0:3000, url: http://localhost:3000` - could the issue be the difference in port names (vs. 127.0.0.1:3000 as registered in the Oauth2 application on OSM?)

When I visit pages that error, I see the following in the node terminal where I've run `yarn dev`
```
error - unhandledRejection: Error: getaddrinfo ENOTFOUND dev-db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'dev-db'
}
Error: getaddrinfo ENOTFOUND dev-db
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'dev-db'
}
```
And finally, when I try to create a new team, I see a 500 error in the browser network tab for the /teams POST request; no action is taken on clicking Submit.

Should I update settings on my config, or am I doing something incorrectly for testing?

**Comment by vgeorge** [comment]
@LanesGood, thanks for the review. There was an issue in the instructions related to the Hydra connection string. I removed Hydra configuration from docker-compose as it is not clear that we are going to use it in the development environment. Can you please do another review? I recommend running `docker-compose down` before the review to clear the existing instances.  

cc @kamicut

**Review by kamicut — APPROVED** [review]
LGTM! I've noticed some pages need multiple clicks, but I don't think we want to block development because they could be UI issues.

**Pull request merged**
